// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: ping-pong.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PingPongServer_PingPong_FullMethodName = "/tls_demo.v1.PingPongServer/PingPong"
)

// PingPongServerClient is the client API for PingPongServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingPongServerClient interface {
	PingPong(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type pingPongServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPingPongServerClient(cc grpc.ClientConnInterface) PingPongServerClient {
	return &pingPongServerClient{cc}
}

func (c *pingPongServerClient) PingPong(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, PingPongServer_PingPong_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingPongServerServer is the server API for PingPongServer service.
// All implementations must embed UnimplementedPingPongServerServer
// for forward compatibility
type PingPongServerServer interface {
	PingPong(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPingPongServerServer()
}

// UnimplementedPingPongServerServer must be embedded to have forward compatible implementations.
type UnimplementedPingPongServerServer struct {
}

func (UnimplementedPingPongServerServer) PingPong(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}
func (UnimplementedPingPongServerServer) mustEmbedUnimplementedPingPongServerServer() {}

// UnsafePingPongServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingPongServerServer will
// result in compilation errors.
type UnsafePingPongServerServer interface {
	mustEmbedUnimplementedPingPongServerServer()
}

func RegisterPingPongServerServer(s grpc.ServiceRegistrar, srv PingPongServerServer) {
	s.RegisterService(&PingPongServer_ServiceDesc, srv)
}

func _PingPongServer_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServerServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingPongServer_PingPong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServerServer).PingPong(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PingPongServer_ServiceDesc is the grpc.ServiceDesc for PingPongServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingPongServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tls_demo.v1.PingPongServer",
	HandlerType: (*PingPongServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _PingPongServer_PingPong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping-pong.proto",
}
